name: grader

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
        
      - name: Install reporter
        continue-on-error: true
        run: dotnet tool install -g dotnet-trx
        
      - name: Run Test 
        continue-on-error: true
        run: dotnet test -l trx; trx
        
      - name: 🧪 show Report
        continue-on-error: true
        if: always()
        run:  
          dotnet tool update -g dotnet-trx ; trx --output

      - name: Autograding
        uses: education/autograding@v1


